version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'  #Change it with your secret password
      MYSQL_ROOT_PASSWORD: 'password' #Change it with your secret password
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
